spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventapp
    username: vimal
    password: vimal
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  jwt:
    secret: "z!7Qh%9Xw3r#Lp2M@b8Fv4Tk^n6Ud1Hy$0Rg5Az"
    expirationMs: 604800000   # 7 days
  file:
    upload-dir: uploads

server:
  port: 8080

logging:
 level:
  org:
  springframework:
   security: DEBUG
 